# QPLEX Configuration for MATE 4v4 environment
name: "QPLEX_4v4_9"
env_name: "MATE-4v4-9"
seed: 42

# Environment settings
env:
  config_file: "mate/assets/MATE-4v4-9.yaml"
  max_episode_steps: 10000
  reward_type: "dense"
  render_mode: "human"  # "human" or "rgb_array"
  window_size: 800

# Training settings
training:
  total_timesteps: 10000000
  learning_starts: 50000
  train_freq: 4
  target_update_interval: 200
  gradient_steps: 1
  batch_size: 32
  buffer_size: 100000
  n_episodes: 1000
  
# Algorithm settings
algorithm:
  name: "QPLEX"
  learning_rate: 0.0005
  gamma: 0.99
  tau: 0.005
  epsilon_start: 1.0
  epsilon_end: 0.05
  epsilon_decay: 0.9999
  dueling: true
  double_q: true
  
# Network architecture
network:
  # Individual Q-networks
  q_network:
    hidden_dims: [256, 256]
    use_rnn: false
    rnn_hidden_dim: 128
    rnn_layers: 2
    rnn_type: "lstm"  # "lstm" or "gru"
    use_attention: false
    num_attention_heads: 4
    dropout: 0.0
    activation: "relu"  # "relu", "tanh", "leaky_relu"
  
  # Mixing network
  mixing_network:
    hidden_dims: [256, 256]
    use_hypernet: true
    dropout: 0.0
    activation: "relu"
  
  # Target network update
  target_update:
    method: "soft"  # "soft" or "hard"
    tau: 0.005

# Agent settings
agents:
  n_agents: 4
  obs_dim: null  # Will be set automatically from environment
  action_dim: null  # Will be set automatically from environment
  state_dim: null  # Will be set automatically from environment
  
# Logging and evaluation
logging:
  log_interval: 1000
  eval_interval: 10000
  save_interval: 100000
  log_dir: "./logs"
  model_dir: "./models"
  tensorboard: true
  wandb: false
  wandb_project: "qplex-mate"
  wandb_entity: null

# Evaluation settings
evaluation:
  n_eval_episodes: 10
  eval_deterministic: true
  render_eval: false
  save_videos: false
  video_dir: "./videos"

# Device settings
device:
  use_cuda: true
  cuda_device: 0

# Reproducibility
reproducibility:
  deterministic: true
  benchmark: false
